#DROP TABLE IF EXISTS `sta_ic_detail_tmp`;
CREATE TABLE `sta_ic_detail_tmp` (
  `ROW_NUM` bigint DEFAULT NULL COMMENT '行号',
  `FLOW_NUM` varchar(255) DEFAULT NULL COMMENT '交易流水',
  `CARD_ID` varchar(255) DEFAULT NULL COMMENT '卡号',
  `CARD_TYPE` int DEFAULT NULL COMMENT '卡类型',
  `TRADE_TYPE` int DEFAULT NULL COMMENT '交易类型',
  `ORG_ID` int DEFAULT NULL COMMENT '组织机构',
  `TRADE_TIME` varchar(255) DEFAULT NULL COMMENT '交易时间',
  `TRADE_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '交易站',
  `MARK_TIME` varchar(255) DEFAULT NULL COMMENT '标注时间',
  `MARK_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '标注站',
  `LINE_ID` int DEFAULT NULL COMMENT '线路',
  `BUS_ID` int DEFAULT NULL COMMENT '车辆',
  `MARK_LINE_ID` int DEFAULT NULL COMMENT '标注线路',
  `MARK_BUS_ID` int DEFAULT NULL COMMENT '标注车辆',
  `DOWN_TIME` varchar(255) DEFAULT NULL COMMENT '下车时间',
  `DOWN_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '下车站点',
  `TRADE_DATE` varchar(255) DEFAULT NULL COMMENT '运营日期',
  `DRIVER_FACE_ID` varchar(255) DEFAULT NULL COMMENT '司售卡号',
  `POS_ID` varchar(255) DEFAULT NULL COMMENT '刷卡机',
  `TRIP_ID` varchar(255) DEFAULT NULL COMMENT '趟次',
  `DIRECTION` int DEFAULT NULL COMMENT '方向',
  `TRANSFER_FLAG` int DEFAULT NULL COMMENT '换乘标记',
  `TRANSFER_ID` varchar(255) DEFAULT NULL COMMENT '出行链编号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='出行表';
ALTER TABLE `sta_ic_detail_tmp` ADD INDEX  TMP_ROW_NUM_INDEX ( `ROW_NUM` );
#truncate table sta_ic_detail_tmp;

#DROP TABLE IF EXISTS `sta_ic_detail`;
CREATE TABLE `sta_ic_detail` (
  `FLOW_NUM` varchar(255) DEFAULT NULL COMMENT '交易流水',
  `CARD_ID` varchar(255) DEFAULT NULL COMMENT '卡号',
  `CARD_TYPE` int DEFAULT NULL COMMENT '卡类型',
  `TRADE_TYPE` int DEFAULT NULL COMMENT '交易类型',
  `ORG_ID` int DEFAULT NULL COMMENT '组织机构',
  `TRADE_TIME` varchar(255) DEFAULT NULL COMMENT '交易时间',
  `TRADE_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '交易站',
  `MARK_TIME` varchar(255) DEFAULT NULL COMMENT '标注时间',
  `MARK_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '标注站',
  `LINE_ID` int DEFAULT NULL COMMENT '线路',
  `BUS_ID` int DEFAULT NULL COMMENT '车辆',
  `MARK_LINE_ID` int DEFAULT NULL COMMENT '标注线路',
  `MARK_BUS_ID` int DEFAULT NULL COMMENT '标注车辆',
  `DOWN_TIME` varchar(255) DEFAULT NULL COMMENT '下车时间',
  `DOWN_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '下车站点',
  `TRADE_DATE` varchar(255) DEFAULT NULL COMMENT '运营日期',
  `DRIVER_FACE_ID` varchar(255) DEFAULT NULL COMMENT '司售卡号',
  `POS_ID` varchar(255) DEFAULT NULL COMMENT '刷卡机',
  `TRIP_ID` varchar(255) DEFAULT NULL COMMENT '趟次',
  `DIRECTION` int DEFAULT NULL COMMENT '方向',
  `TRANSFER_FLAG` int DEFAULT NULL COMMENT '换乘标记',
  `TRANSFER_ID` varchar(255) DEFAULT NULL COMMENT '出行链编号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='出行表';
#truncate table sta_ic_detail;

#DROP TABLE IF EXISTS `trip_chain_ex`;
CREATE TABLE `trip_chain_ex` (
  `CARD_ID` varchar(255) DEFAULT NULL COMMENT '卡号',
  `TRADE_DATE` varchar(255) DEFAULT NULL COMMENT '运营日期',
  `TRANSFER_ID` varchar(255) DEFAULT NULL COMMENT '出行链编号',
  `ON_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '上车站点',
  `ON_TIME` varchar(255) DEFAULT NULL COMMENT '上车时间',
  `ON_TIME_BUCKET` varchar(255) DEFAULT NULL COMMENT '上车时段',
  `DOWN_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '下车站点',
  `DOWN_TIME` varchar(255) DEFAULT NULL COMMENT '下车时间',
  `DOWN_TIME_BUCKET` varchar(255) DEFAULT NULL COMMENT '下车时段',
  `LINE` varchar(255) DEFAULT NULL COMMENT '线路',
  `TRANSFER_STATION` varchar(255) DEFAULT NULL COMMENT '换乘站',
  `TRANSFER_NUM` int DEFAULT NULL COMMENT '换乘次数'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='出行链表';
#truncate table trip_chain_ex;

#DROP TABLE IF EXISTS `commuter_trip_chain`;
CREATE TABLE `commuter_trip_chain` (
  `CARD_ID` varchar(255) DEFAULT NULL COMMENT '卡号',
  `TRADE_DATE` varchar(255) DEFAULT NULL COMMENT '运营日期',
  `FORWARD_ON_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '去程上车站点',
  `FORWARD_DOWN_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '去程下车站点',
  `FORWARD_ON_TIME_BUCKET` varchar(255) DEFAULT NULL COMMENT '去程上车时段',
  `FORWARD_LINE` varchar(255) DEFAULT NULL COMMENT '去程线路过程',
  `FORWARD_TRANSFER_STATION` varchar(255) DEFAULT NULL COMMENT '去程换乘过程',
  `BACK_ON_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '回程上车站点',
  `BACK_DOWN_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '回程下车站点',
  `BACK_ON_TIME_BUCKET` varchar(255) DEFAULT NULL COMMENT '回程上车时段',
  `BACK_LINE` varchar(255) DEFAULT NULL COMMENT '回程线路过程',
  `BACK_TRANSFER_STATION` varchar(255) DEFAULT NULL COMMENT '回程换乘过程'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='通勤出行链表';
#truncate table commuter_trip_chain;

#DROP TABLE IF EXISTS `commuter_law`;
CREATE TABLE `commuter_law` (
  `CARD_ID` varchar(255) DEFAULT NULL COMMENT '卡号',
  `RESIDENCE_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '最频住站',
  `OCCUPATION_STATION_NAME` varchar(255) DEFAULT NULL COMMENT '最频职站',
  `FORWARD_LINE` varchar(255) DEFAULT NULL COMMENT '最频去程线路过程',
  `FORWARD_ON_TIME_BUCKET` varchar(255) DEFAULT NULL COMMENT '最频去程时段',
  `FORWARD_TRANSFER_STATION` varchar(255) DEFAULT NULL COMMENT '最频去程换乘过程',
  `BACK_LINE` varchar(255) DEFAULT NULL COMMENT '最频回程线路过程',
  `BACK_ON_TIME_BUCKET` varchar(255) DEFAULT NULL COMMENT '最频回程时段',
  `BACK_TRANSFER_STATION` varchar(255) DEFAULT NULL COMMENT '最频回程换乘过程',
  `LAW_STATION_NUM` int DEFAULT NULL COMMENT '最频站点数量',
  `LAW_LINE_NUM` int DEFAULT NULL COMMENT '最频线路过程数量',
  `LAW_TRANSFER_NUM` int DEFAULT NULL COMMENT '最频换乘过程数量',
  `LAW_TIME_NUM` int DEFAULT NULL COMMENT '最频出行时段数量',
  `DAY_NUM` int DEFAULT NULL COMMENT '出行天数',
  `LAW_STATION_NUM_PREPED` DOUBLE NULL DEFAULT NULL COMMENT '最频站点数量归一化',
	`LAW_LINE_NUM_PREPED` DOUBLE NULL DEFAULT NULL COMMENT '最频线路过程数量归一化',
	`LAW_TIME_NUM_PREPED` DOUBLE NULL DEFAULT NULL COMMENT '最频出行时段数量归一化',
	`DAY_NUM_PREPED` DOUBLE NULL DEFAULT NULL COMMENT '出行天数归一化',
  `SCORE` double(14,12) DEFAULT NULL COMMENT '规律度评分',
  `CLUSTER` VARCHAR(3) DEFAULT NULL COMMENT '类别'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='通勤规律表';
#truncate table commuter_law;

#DROP TABLE IF EXISTS `commuter_preprocessed_tmp`;
CREATE TABLE `commuter_preprocessed_tmp` (
  `CARD_ID` varchar(255) DEFAULT NULL COMMENT '卡号',
  `LAW_STATION_NUM_PREPED` DOUBLE DEFAULT NULL COMMENT '最频站点数量预处理结果',
  `LAW_LINE_NUM_PREPED` DOUBLE DEFAULT NULL COMMENT '最频线路过程数量预处理结果',
  `LAW_TIME_NUM_PREPED` DOUBLE DEFAULT NULL COMMENT '最频出行时段数量预处理结果',
  `DAY_NUM_PREPED` DOUBLE DEFAULT NULL COMMENT '出行天数预处理结果'
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='通勤特征预处理结果表';
  ALTER TABLE `commuter_preprocessed_tmp` ADD INDEX  CARD_ID_INDEX0 ( `CARD_ID` );
#truncate table commuter_preprocessed_tmp;


#DROP TABLE IF EXISTS `commuter_score_tmp`;
create table commuter_score_tmp
 (
 `CARD_ID` varchar(255) DEFAULT NULL COMMENT '卡号',
 `SCORE` double(14,12) DEFAULT NULL COMMENT '规律度评分'
 ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='通勤打分临时表';
 ALTER TABLE `commuter_score_tmp` ADD INDEX  CARD_ID_INDEX ( `CARD_ID` );
 
 #DROP TABLE IF EXISTS `commuter_cluster_tmp`;
CREATE TABLE `commuter_cluster_tmp` (
  `CARD_ID` varchar(255) DEFAULT NULL COMMENT '卡号',
  `CLUSTER` VARCHAR(3) DEFAULT NULL COMMENT '类别'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='通勤归类临时表';
ALTER TABLE `commuter_cluster_tmp` ADD INDEX  CARD_ID_INDEX1 ( `CARD_ID` );
#truncate table commuter_cluster_tmp;
 